name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Remove existing code
        run: |
          sudo rm -rf /home/ubuntu/EmployeeOS_F13
          mkdir -p /home/ubuntu/EmployeeOS_F13

      - name: Clone repository
        run: |
          git clone https://github.com/your-username/your-repo.git /home/ubuntu/EmployeeOS_F13
          cd /home/ubuntu/EmployeeOS_F13

      - name: Install dependencies and build
        run: |
          cd /home/ubuntu/EmployeeOS_F13
          npm install
          npm run build

      - name: Move build folder to web directory
        run: |
          sudo rm -rf /var/www/html/employeeos
          sudo mv /home/ubuntu/EmployeeOS_F13/dist /var/www/html/employeeos
          sudo chown -R www-data:www-data /var/www/html/employeeos
          sudo chmod -R
